name: implicitly_animated_reorderable_list_2
description: A Flutter ListView that implicitly animates between the changes of
  two lists with the support to reorder its items.
version: 0.6.0
homepage: https://github.com/theniceboy/implicitly_animated_reorderable_list_2/tree/master/example/lib/ui

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  async: ^2.8.1
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
